- name: Change_MOTD
  hosts: all
  become: yes
  vars:
    motd_message: "Hello in brainless world \n"

  tasks:
    - name: Set_MOTD
      copy:
        content: |
          {{ motd_message }}
        dest: /etc/motd
        owner: root
        group: root
        mode: '0644'
        backup: yes

    - name: Ensure_SSH_uses_MOTD
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PrintMotd'
        line: 'PrintMotd yes'
      notify: restart ssh

  handlers:
    - name: restart_ssh
      systemd:
        name: ssh
        state: restarted